export const FETCH_WEATHER_REQUESTED = "FETCH_WEATHER_REQUESTED";
export const FETCH_WEATHER_SUCCESS = "FETCH_WEATHER_SUCCESS";
export const FETCH_WEATHER_FAILED = "FETCH_WEATHER_FAILED";
export const TOGGLE_LOADING = "TOGGLE_LOADING";
