export const FETCH_WEATHER_REQUESTED = 'FETCH_WEATHER_REQUESTED';
export const FETCH_REGIONS_REQUESTED = 'FETCH_REGIONS_REQUESTED';
export const FETCH_COUNTRY_CODES_REQUESTED = 'FETCH_COUNTRY_CODES_REQUESTED';
export const FETCH_WEATHER_SUCCESS = 'FETCH_WEATHER_SUCCESS';
export const FETCH_WEATHER_FAILED = 'FETCH_WEATHER_FAILED';
